Description: >
    Mario Rodriguez - AWS portion of CircleCI and AWS pipeline

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
Resources:

  BlueGreenS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BlueGreenBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublicS3BlueGreenBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BlueGreenS3Bucket
                - /*
      Bucket: !Ref BlueGreenS3Bucket

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - BlueGreenS3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - BlueGreenS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
