version: 2.1
commands:
  dependencies:
    steps:
      - run: yum -y install tar less gzip #needed to attach_workspace
workflows:
  deploy_workflow:
    jobs:
      - create_and_deploy_front_end:
          context: aws
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create S3 bucket"
          command:
            aws cloudformation deploy --template-file bucket.yml --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - dependencies
      - run:
          name: "Query for last deployment id"
          command: |
            cd /home/circleci/project
            aws cloudformation list-exports \
            --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text >> last_deploy_id
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - dependencies
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "Production distro"
          command: |
            aws cloudformation deploy --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"
  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - dependencies
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "Production distro"
          command: |
            PreviousPipelineID=$(cat /home/circleci/last_deploy_id)
            aws s3 rm "s3://${OldPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
            





