version: 2.1

commands:
  dependencies:
    steps:
      - run: yum -y install tar less gzip #needed to attach_workspace
  unique_name:
    steps:
      - run:
          name: Set Environment Variable 
          command: |
            echo "UNIQUE_NAME=$CIRCLE_PROJECT_REPONAME$CIRCLE_WORKFLOW_ID" >> $BASH_ENV

workflows:
  blue_green_workflow:
    jobs:
      - test_variables:
          context: aws
      - create_and_deploy_front_end:
          context: aws
      - promote_to_production:
          requires: 
            - create_and_deploy_front_end

jobs:
  test_variables:
    docker:
      - image: amazon/aws-cli
    steps:
      - unique_name
      - run:
          name: "Test var expansion"
          command: |
            echo $UNIQUE_NAME
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - unique_name
      - run: |
          aws cloudformation deploy \
          --template-file bucket.yml \
          --stack-name ${UNIQUE_NAME} \
          --parameter-overrides NAME=${UNIQUE_NAME}
      - run: aws s3 sync . s3://${UNIQUE_NAME} --delete

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - unique_name
      - dependencies
      - run:
          name: "Query for last deployment id"
          command: |
            cd /home/circleci/project
            aws cloudformation list-exports \
            --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text >> last_deploy_id
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - dependencies
      - unique_name
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "Production distro"
          command: |
            aws cloudformation deploy --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${UNIQUE_NAME}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - unique_name
      - dependencies
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "Production distro"
          command: |
            PreviousPipelineID=$(cat /home/circleci/last_deploy_id)
            aws s3 rm "s3://${PreviousPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
            





